#!/bin/bash

case "$OSTYPE" in
  solaris*) echo "SOLARIS" ;;
  darwin*)  echo "OSX" ;;
  linux*)   echo "LINUX" ;;
  bsd*)     echo "BSD" ;;
  msys*)    echo "WIN" ;;
  cygwin*)  echo "WIN" ;;
  *)        echo "unknown: $OSTYPE" ;;
esac
