#!/bin/bash

url="$( git config remote.origin.url | sed -e "s/git@github.com:/https:\/\/github.com\//g" )"
if [ "${url:(-4)}" == ".git" ]; then
    url="$( echo "${url%.*}" )"
fi

if [ -z "${url}" ]; then
    echo -e "${B_RED}${T_WHITE}ERROR:${F_RESET} no repository or url found"
    exit 1
fi

echo "$url"