#!/bin/bash

# Requires:
# https://github.com/sindresorhus/clipboard-cli
# npm install -g clipboard-cli

url="https://www.npmjs.com/package"
value="$( clipboard )"
if [[ -n $value ]]; then
    url="$url/$value"
fi

${BROWSER} ${url}
