#!/bin/bash

base="dev" #default base branch
if [[ ! -z $1 ]]; then
base="$1"
fi

url="$( get_repo_url )"
current="$( git branch --show-current )"
if [ "$current" != "${base}" ]; then
    url="${url}/compare/${base}...${current}"
else
    url="${url}/compare/${base}..."
fi
${BROWSER} ${url}
