#!/bin/bash

# Zinit
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"

# NVM
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export NVM_LAZY=1

# Prompt
if [ "$USE_PROMPT" = "p10k" ]; then
    zinit ice depth"1" # git clone depth
    zinit light romkatv/powerlevel10k
elif [ "$USE_PROMPT" = "starship" ]; then
    zinit ice as"command" from"gh-r" \
        atclone"./starship init zsh > init.zsh; ./starship completions zsh > _starship" \
        atpull"%atclone" src"init.zsh"
    zinit light starship/starship
fi

# Plugins
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-history-substring-search
zinit light agkozak/zsh-z

# Snippets
zinit snippet OMZP::1password
zinit snippet OMZP::brew
zinit snippet OMZP::git
zinit snippet OMZP::node
zinit snippet OMZP::sudo
zinit snippet OMZP::vscode
zinit snippet OMZP::web-search

# OMZ Libraries
zinit snippet OMZL::directories.zsh
zinit snippet OMZL::functions.zsh #take
zinit snippet OMZL::git.zsh
zinit snippet OMZL::history.zsh

# Lazy loading
zinit wait lucid atload'_zsh_autosuggest_start' light-mode for zsh-users/zsh-autosuggestions
zinit wait lucid atload'enable_you_should_use' light-mode for MichaelAquilina/zsh-you-should-use
zinit wait lucid light-mode for agkozak/zhooks
zinit wait lucid light-mode for Aloxaf/fzf-tab
zinit ice wait"0" lucid
zinit snippet OMZP::nvm
zinit ice wait"0" lucid
zinit light zdharma-continuum/fast-syntax-highlighting

# Turbo
autoload -Uz compinit
compinit
zinit cdreplay -q

# Keybindings
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Plugins Config
unset ZSH_AUTOSUGGEST_USE_ASYNC
