#!/bin/bash

line="$1"

# Title
if [[ "${line:0:2}" == "# " ]]; then
    line="${F_UNDERLINE}${F_BOLD}${line}${F_RESET}"
fi

# Subtitle
if [[ "${line:0:3}" == "## " ]]; then
    line="${F_BOLD}${line}${F_RESET}"
fi


# **Bold**
line=$(echo ${line} | sed -r "s/\*\*([^\s][^\*]+?[^\s])\*\*/«\1»/g")
line=${line//«/${F_BOLD}}
line=${line//»/${F_RESET}}

# TODO: *Itallic* 
#line=$(echo -e ${line} | sed -r "s/\*([^\s][^\*]+?[^\s])\*/«\1»/g")
#line=${line//«/${F_ITALIC}}
#line=${line//»/${F_RESET}}

# Horizontal Line --- 
if [[ "${line:0:3}" == "---" ]]; then
    line=$(printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -)
    line="${F_DIM}${line}${F_RESET}"
fi

# `Code`
line=$(echo -e ${line} | sed -r "s/\`([^\s][^\`]+?[^\s])\`/«\1»/g")
line=${line//«/${T_YELLOW}\`}
line=${line//»/${T_YELLOW}\`${T_NC}}

# <params>`
line=${line//</${T_CYAN}<}
line=${line//>/${T_CYAN}>${T_NC}}

# Icons
line=${line//⚠/${F_BOLD}${T_YELLOW}⚠${T_NC}}
line=${line//✔/${F_BOLD}${T_GREEN}✔${T_NC}}
line=${line//✅/${F_BOLD}${T_GREEN}✅${T_NC}}
line=${line//✘/${F_BOLD}${T_RED}✘${T_NC}}
line=${line//⛔/${F_BOLD}${T_RED}⛔${T_NC}}

echo -e "${line}"