#!/bin/bash

# VSCode
alias vc="code --new-window --profile Default"
alias vco=".open_code -p Default"
alias vd="code --new-window --profile DotNet"
alias vdo=".open_code -p DotNet"
alias vr="code --new-window --profile React"
alias vro=".open_code -p React"
alias vn="code --new-window --profile Node"
alias vno=".open_code -p Node"

# Extensions
# npm install -g vsce
alias vcp="vsce package --out build/"