#!/bin/bash

# VSCode
alias vc="code --profile \"Default\""
alias vco="vc ."
alias vcn="vc . -n"
alias vd="code --profile \"DotNet\""
alias vdo="vd ."
alias vdn="vd . n"
alias vr="code --profile \"React\""
alias vro="vr ."
alias vn="code --profile \"Node\""
alias vno="vn ."

# Extensions
# npm install -g vsce
alias vcp="vsce package --out build/"