#!/bin/bash

# VSCode
alias vc="code --new-window --profile Default"
alias vco="code --new-window --profile Default ."
alias vcr="code --new-window --profile Default --remote wsl+Ubuntu --goto \"`pwd`\"/"
alias vd="code --new-window --profile DotNet"
alias vdo="code --new-window --profile DotNet ."
alias vdr="code --new-window --profile DotNet --remote wsl+Ubuntu --goto \"`pwd`\"/"
alias vr="code --new-window --profile React"
alias vro="code --new-window --profile React ."
alias vrr="code --new-window --profile React --remote wsl+Ubuntu --goto \"`pwd`\"/"
alias vn="code --new-window --profile Node"
alias vno="code --new-window --profile Node ."
alias vnr="code --new-window --profile Node --remote wsl+Ubuntu --goto \"`pwd`\"/"

# Extensions
# npm install -g vsce
alias vcp="vsce package --out build/"