#!/bin/bash

# Open
alias o=".open_path -p ." # open current folder
alias op=".open_path -p" # <path>
alias opb=".open_path -p build" # open build path
alias opc=".open_path -p coverage" # open coverage path

# Browse
alias b=".open_browser -f ./index.html" # browse index.html
alias bu=".open_browser -u" # <url>
alias blh=".open_browser -u http://localhost"
alias blhp=".open_browser -u http://localhost -p" # <port>
alias bcr=".open_browser -f coverage" # browse coverage
alias cgr=".copy_git_repo" # copy git repo url to clipboard
alias bgr=".open_git_repo" # browse git repo
alias bgb=".open_git_branch" # browse git repo on current branch
alias bgp=".open_git_pull" # browse git repo pulls
alias bgc=".open_git_compare" # <base-branch>
alias bnp=".open_npm_package" #browse npm package
alias bnc=".open_npm_clipboard" #browse npm package from clipboard

# Search
alias s=".search_text" # -t <text> [-p <path>]
alias sff="find " # <path> -type d -name <folder>

# Base 64
alias b2f=".b64_to_file"
alias f2b=".file_to_b64"
