#!/bin/bash

# Git
alias gcum="git config user.name \"${GIT_USER_NAME}\" && git config user.email \"${GIT_USER_EMAIL}\""
alias gcu="git config credential.username \"${GIT_USER_NAME}\""
alias gc="gcu && gcum"
alias ghcum="git config user.name \"${GITHUB_USER_NAME}\" && git config user.email \"${GITHUB_USER_EMAIL}\""
alias ghcu="git config credential.username \"${GITHUB_USER_NAME}\""
alias gcg="git config --edit --global"
alias gcl="git config --edit --local"
alias guc="git reset --hard HEAD" # undo changes and preserve untracked files
alias gca="git clean -f -d -x" # clean ALL changes and remove untracked files
alias gcd="git checkout dev"
alias glod="git pull origin dev"
alias gpnv="git push --no-verify"
alias gcae="git commit --allow-empty -m " # <message>