#!/bin/bash

# Use Windos Git with Credentials Manager
alias git=git.exe

# Git
alias gcgm="git config --global init.defaultBranch main"
alias gcg="git config --edit --global"
alias gcl="git config --edit --local"
alias guc="git reset --hard HEAD" # undo changes and preserve untracked files
alias gca="git clean -f -d -x" # clean ALL changes and remove untracked files
alias gcd="git checkout dev"
alias glod="git pull origin dev"
alias glom="git pull origin main"
alias gpnv="git push --no-verify"
alias gcae="git commit --allow-empty -m " # <message>