#!/bin/bash

# https://github.com/deinsoftware/swpm
# npm install -g swpm
# Switch Packages Manager
alias sin="swpm --info"

alias sip="swpm init"
alias sipy="swpm init -y"
alias scl="swpm config list"
alias sccf="swpm cache clean --force"

alias sci="sca && si"

# Run
alias srb="sr build"
alias srbd="sr build:dev"
alias srd="sr deploy"
alias srs="sr start"
alias srd="sr dev"
alias srsd="sr start:dev"
alias srsq="sr start:qa"
alias srss="sr start:stg"
alias srsp="sr start:prod"
alias srt="sr test"
alias srtui="sr test:ui"
alias srtc="sr test:c"
alias srtw="sr test:w"
alias srtwc="sr test:wc"

# Pubish
alias sp="swpm publish"
alias su="swpm unpublish" # <package@version>

# Updates
alias spl="swpm list --depth 0 -g" #list global packages installed
alias spo="swpm outdated -g"
alias suig="sui -g"
