#!/bin/bash

# Packages
alias xcl="swpx npm-check"
alias xcg="swpx npm-check -g"
alias xul="swpx npm-check -u"
alias xug="swpx npm-check -gu"

# Files and Ports
alias xpk="swpx npkill" #clean unused node_modules
alias xkp="swpx kill-port" # <port>
alias xfk="swpx fkill-cli" # [<pid|name|:port> …] #kill processes

# Image Optimizer
alias iow="swpx @squoosh/cli --webp auto" # <file-name>
alias ioa="swpx @squoosh/cli --avif auto" # <file-name>
alias iop="swpx @squoosh/cli --oxipng auto" # <file-name>

# Live Server
alias svd="swpx vite dev"