#!/bin/bash

alias c="clear"
alias x="exit"
alias e="vc ~/ ~/.zshrc ~/.aliases ~/.colors ~/.hooks"
alias er="vcr ~/ ~/.zshrc ~/.aliases ~/.colors ~/.hooks"
alias r="source ~/.zshrc"

alias zs="zsh_stats"
alias mu="history -10"
alias hc="history -c"
alias hg="history | grep" # <command>
alias ag="alias | grep" # <command>
