#!/bin/bash

alias c="clear"
alias x="exit"
alias e="code --profile \"Default\" -n ~/ ~/.zshrc ~/.aliases ~/.colors ~/.hooks"
alias r="source ~/.zshrc"

alias mu="history -10"
alias hc="history -c"
alias hg="history | grep" # <command>
alias ag="alias | grep" # <command>

alias mu="history | awk ' "