#!/bin/bash

# https://github.com/abishekvashok/cmatrix
# sudo apt install cmatrix / brew install cmatrix
alias m="cmatrix -abs"

# https://htop.dev/
# sudo apt install htop / brew install htop
alias t="htop"

# https://dev.yorhel.nl/ncdu
# sudo apt install ncdu / brew install ncdu
alias d="ncdu --exclude /mnt --color dark" # <path>

# https://the.exa.website/install/linux
# apt install exa
alias et='exa --icons --tree'
alias et1='exa --icons --tree --level=1 --ignore-glob="*node_modules*"'
alias et2='exa --icons --tree --level=2 --ignore-glob="*node_modules*"'
alias els='exa --long'
alias ela='exa --long --all'

# https://www.speedtest.net/apps/cli
# speed test
alias sp='speedtest'
