#!/bin/bash

# https://www.speedtest.net/apps/cli
alias st="speedtest"

# https://github.com/sindresorhus/clipboard-cli
# sag clipboard-cli
alias cb="clipboard"

# https://www.npmjs.com/package/trash-cli
# sag trash-cli
alias rm="trash"

# https://www.npmjs.com/package/internal-ip-cli
# sag internal-ip-cli
alias ipl="internal-ip"

# https://www.npmjs.com/package/public-ip-cli
# sag public-ip-cli
alias ipp="public-ip"
