#!/bin/bash

osascript <<-EOF
    set cmds to {"sndcpy", "scrcpy"}

    tell application "iTerm"
        activate
        create window with default profile

        tell current session of current window
            split vertically with default profile
        end tell

        tell first session of current tab of current window
            write text "sndcpy"
        end tell
        tell second session of current tab of current window
            write text "scrcpy"
        end tell

    end tell
EOF
