#!/bin/bash

line="$1"
border="$2"


if [ "${border}" == "true" ]; then
    # align columns
    line=$(echo -e ${line} | sed 's/|/¶|/g' | column -s '¶' -t)
    
    line="${line//\|/${T_BLACK}\| ${T_NC}}"
else
    # align columns
    line=$(echo -e ${line} | column -s '|' -t)
fi

echo -e "${line}"