#!/bin/bash

while getopts ":s:" opt; do
    case $opt in
        s) sheet="${OPTARG}"
        ;;
        \?) echo "Invalid option -${OPTARG}" >&2
        exit 1
        ;;
    esac
done

create_table(){
    text="$1"
    if [[ -z "$table" ]]; then
        text=$(md_table_title "${text}")
    else
        if [[ "${text:0:2}" == "|-" ]]; then
            text="" #remove division
        else
            text=$(md_table_row "${text}")
            text=$(md_format_text "${text}")
        fi
    fi
    table+="${text}\n"
}

print_table(){
    text="$1"
    if [ ! -z "${text}" ]; then
        table=$(md_format_table "${text}" "false")
        tput rmam
        echo -e "$table"
        tput smam
        table=""
    fi
}

table=""
if [[ $# -eq 0 ]]; then
    # go to cheatsheet menu
    exit 1
else
    while IFS= read -r line
    do
        if [[ "${line}" == \|* ]]; then
            create_table "${line}"
        else
            print_table "${table}"
            line=$(md_format_text "${line}")
            echo -e "${line}"
        fi
    done < ~/.dotfiles/cheatsheet/${sheet}.md
    print_table "${table}"
fi