#!/bin/bash

[[ $# -eq 0 ]] && Return
NAME=${1}
OPTIONS=${2---use-npm}
echo "\e[32m❯ \e[33mCreating...\e[0m"
eval "npx create-react-app ${NAME} ${OPTIONS}"
echo "\e[32m❯ \e[33mChanging dir...\e[0m"
cd $NAME
echo "\e[32m❯ \e[33mOpening...\e[0m"
code .
nei