#!/bin/bash

[[ $# -eq 0 ]] && return
NAME=${1}
OPTIONS=${2---use-npm}
echo "${T_GREEN}❯ ${T_YELLOW}Creating...${f_reset}"
eval "${(P)${:-${PACKAGE_PIN:-$PACKAGE}_RUN}} create-react-app ${NAME} ${OPTIONS}"
echo "${T_GREEN}❯ ${T_YELLOW}Changing dir...${f_reset}"
cd $NAME
echo "${T_GREEN}❯ ${T_YELLOW}Opening...${f_reset}"
code .
nei