#!/bin/bash

[[ $# -eq 0 ]] && return
NAME=${1}
TEMPLATE=${2---template react-ts}
echo "${T_GREEN}❯ ${T_YELLOW}Creating...${f_reset}"
eval "${(P){:-${PACKAGE_PIN:-$PACKAGE}}} init @vitejs/app ${NAME} ${TEMPLATE}"
echo "${T_GREEN}❯ ${T_YELLOW}Changing dir...${f_reset}"
cd $NAME
echo "${T_GREEN}❯ ${T_YELLOW}Installing...${f_reset}"
npm i
nei
echo "${T_GREEN}❯ ${T_YELLOW}Opening...${f_reset}"
code .
echo "${T_GREEN}❯ ${T_YELLOW}Runing dev...${f_reset}"
npm run dev