#!/bin/bash

after_validation(){
    install_packages=""
    if [[ -f "$config_file" ]]; then
        install_packages="&& ${install_frozen}"
    fi

    # create branch
    if [[ "$cmd" =~ ^"git checkout -b " ]] || [[ "$cmd" =~ ^"gcb " ]]; then
        ask_cancel_after "gpsup && git pull ${install_packages}"
    elif [[ "$cmd" =~ ^"git switch -c" ]] || [[ "$cmd" =~ ^"gswc" ]]; then
        ask_cancel_after "gpsup && git pull ${install_packages}"
    # pull and merge from origin
    elif [[ -f "$config_file" ]] && ( [[ "$cmd" =~ ^"git pull origin" ]] || [[ "$cmd" =~ ^"gl origin" ]] ); then
        ask_cancel_after "${install_frozen}"
    # pull
    elif [[ -f "$config_file" ]] && ( [[ "$cmd" =~ ^"git pull" ]] || [[ "$cmd" =~ ^"gl" ]] ); then
        ask_cancel_after "${install_frozen}"
    # switch branch
    elif [[ "$cmd" =~ ^"git checkout -b " ]] || [[ "$cmd" =~ ^"gcb " ]]; then
        ask_cancel_after "gpsup && git pull ${install_packages}"
    elif [[ "$cmd" =~ ^"git checkout" ]] || [[ "$cmd" =~ ^"gco" ]] || [[ "$cmd" =~ ^"gcd" ]]; then
        ask_cancel_after "git pull ${install_packages}"
    elif [[ "$cmd" =~ ^"git switch" ]] || [[ "$cmd" =~ ^"gsw" ]]; then
        ask_cancel_after "git pull ${install_packages}"
    elif [[ "$cmd" =~ ^"gswd" ]] || [[ "$cmd" =~ ^"gswm" ]]; then
        ask_cancel_after "git pull ${install_packages}"
    fi
}

pos_cmd_validation() {
    [[ -z $cmd ]] && return # If there's no cmd, return. Else...

    if [[ "$quit" == "n" ]]; then
        after_validation
    fi

    quit="y"
}

add-zsh-hook precmd pos_cmd_validation        # Adds the pos hook
# add-zsh-hook -d precmd pos_cmd_validation   # Remove it for this hook
