#!/bin/bash

# Android Debug Bus
# brew install --cask android-platform-tools
alias ad="adb devices"

# Screen Copy
# brew install scrcpy
alias scp="scrcpy --no-audio"
alias snd="scrcpy"
alias scpi="scrcpy --no-audio --show-touches --mouse=aoa --keyboard=aoa"
alias scpr="take ~/Documents/recordings && scrcpy --no-audio --show-touches --record=android-screen-$(date +%Y%m%d-%H%M%S).mp4 && cd -"

if [[ "$( which_os )" == "OSX" ]]; then
    alias sdc="caffeinate -s scrcpy"
fi
