#!/bin/bash

# VSCode
alias vc=".vscode" # <path> | "<paths> [-n]"
alias vci=".vscode -n -i" # <path> | "<paths>"
alias vcd=".vscode -p DotNet -n -i" # <path> | "<paths>"
alias vcr=".vscode -p React -n -i" # <path> | "<paths>"
alias vcn=".vscode -p Node -n -i" # <path> | "<paths>"
alias vcb=".vscode -p Bun -n -i" # <path> | "<paths>"

# Extensions
# sag vsce
alias vcp="vsce package --out build/"
