#!/bin/bash

# Insiders
alias codi="code-insiders"

# VSCode
alias vc=".open_code " # <path|file>
alias vci=".open_code -i" # <path|file>
alias vcd=".open_code -p DotNet -i" # <path|file>
alias vcr=".open_code -p React -i" # <path|file>
alias vcn=".open_code -p Node -i" # <path|file>
alias vcb=".open_code -p Bun -i" # <path|file>

# Extensions
# sag vsce
alias vcp="vsce package --out build/"