#!/bin/bash

# Open
alias o=".open_path -p ." # open current folder
alias soeb="soe build" # open build path
alias soec="soe coverage" # open coverage path

# Browse
alias b=".open_browser -f ./index.html" # browse index.html
alias bu=".open_browser -u" # <url>
alias blh=".open_browser -u http://localhost"
alias blhp=".open_browser -u http://localhost -p" # <port>
alias cgr=".copy_git_repo" # copy git repo url to clipboard
alias bnc=".open_npm_clipboard" #browse npm package from clipboard

# Search
alias s=".search_text" # -t <text> [-p <path>]
alias sff="find " # <path> -type d -name <folder>

# Base 64
alias b2f=".b64_to_file" # -e <ext>
alias f2b=".file_to_b64"
