#!/bin/bash

# brew install fzf
# brew install bat
alias f="fzf"
alias fzp='fzf --preview="bat --color=always {}"'
alias fzc='.vscode $(fzf --multi --preview="bat --color=always {}")' # use tab for multiple selection
alias fzi='.vscode $(fzf --multi --preview="bat --color=always {}") -i -n' # use tab for multiple selection

alias fco='git branch | fzf | cut -c 3- | xargs git checkout'

# Tricks
# cd <path>/** <tab>
# kill -9 ** <tab>
