#!/bin/bash

# Git
alias gkm="git config --global init.defaultBranch ${MAIN}"
alias gkg="git config --edit --global"
alias gkl="git config --edit --local"
alias guc="git reset --hard HEAD" # undo changes and preserve untracked files
alias gca="git clean -f -d -x" # clean ALL changes and remove untracked files
alias gral="git checkout -- ." #revert at last commit
alias gcd="git checkout ${DEV}"
alias gcm="git checkout ${MAIN}"
alias glod="git pull origin ${DEV}"
alias glom="git pull origin ${MAIN}"
alias gpnv="git push --no-verify"
alias gce="git commit --allow-empty -m " # <message>

# Precommit
alias pcsc="PRE_COMMIT_ALLOW_NO_CONFIG=1" # skip pre-commit config

# https://github.com/Everduin94/better-commits
# sag better-commits
alias gbc="better-commits"
alias gbb="better-branch"