#!/bin/bash

# Git

# git config main as default branch
alias gkm="git config --global init.defaultBranch $(git_main_branch)"
# git konfig global
alias gkg="git config --edit --global"
# git konfig local
alias gkl="git config --edit --local"
# git undo changes
alias guc="git reset --hard HEAD" # undo changes and preserve untracked files
# git clean all
alias gca="git clean -f -d -x" # clean ALL changes and remove untracked files
# git revert at last commit
alias gral="git checkout -- ." #revert at last commit
# git checkout develop
alias gcd="git checkout $(git_develop_branch)"
# git checkout main/master
alias gcm="git checkout $(git_main_branch)"
# git pull origin develop
alias glod="git pull origin $(git_develop_branch)"
#git pull origin main/master
alias glom="git pull origin $(git_main_branch)"
# git push no verify
alias gpnv="git push --no-verify"
# git commit empty
alias gce="git commit --allow-empty -m " # <message>
# git re-commit
alias grc="git commit --amend --no-edit && git push -f"

# https://github.com/Everduin94/better-commits
# sag better-commits
alias gbc="better-commits"
alias gbb="better-branch"