#!/bin/bash

#XCode reinstall
alias xcd="sudo rm -rf /Library/Developer/CommandLineTools"
alias xci="sudo xcode-select --install"
alias xcr="sudo xcode-select -r"

# https://github.com/abishekvashok/cmatrix
# brew install cmatrix
alias m="cmatrix -abs"
