#!/bin/bash

alias c="clear"
alias x="exit"
alias e=".open_code -p Default -f \"~/.dotfiles/ ~/.zshrc ~/.dotfiles/.aliases ~/.dotfiles/.colors ~/.dotfiles/.hooks\" -n -i"
alias r="source ~/.zshrc"

alias zs="zsh_stats"
alias mu="history -10"
alias hc="history -c"
alias hg="history | grep" # <command>
alias ag="alias | grep" # <command>

alias rf="rm -rf " # <dir|file>
