#!/bin/bash

# Volta
alias vil="volta install node@lts"
alias vpl="volta pin node@18.12.0 && volta pin npm@8.19.2"
alias vi19="volta install node@19"
alias vp19="volta pin node@19.0.0 && volta pin npm@8.19.2"
alias vla="volta list all"
alias vln="volta list node"
alias vlc="volta list node --current --format plain"
alias vld="volta list node --default --format plain"
alias vlp="volta list npm"
alias vcv="node -v && npm -v"

# Delete versions
# unix:     ~/.volta/tools/image/node/
# win:      %LOCALAPPDATA%/Volta/tools/image/node/
# git bash: $(cygpath $LOCALAPPDATA)/Volta/tools/image/node/