#!/bin/bash

if [ "$USE_MANAGER" = "zinit" ]; then
    alias ziud="zinit update --parallel"
    alias zit="zinit times"
    alias zist="zinit status"
    alias zisl="zinit snippets"
    alias zipl="zinit plugins"
fi