#!/bin/bash

while getopts ":e:p:" opt; do
    case $opt in
        e) ext="${OPTARG}"
        ;;
        p) path="${OPTARG}"
        ;;
        \?) echo "Invalid option -${OPTARG}" >&2
        exit 1
        ;;
    esac
done

[[ $# -eq 0 ]] && return
local last="${@: -1}"
local rest="${@:1:${#}-1}"
local cmd=""
local dir="$(basename "$1" .git)"
if [[ -z $rest ]]; then
    cmd="$last"
else
    cmd="$rest $last"
    if [[ !"$last" =~ ^"-" ]]; then
        dir="$last"
    fi
fi
echo "${T_GREEN}❯ ${T_YELLOW}Cloning...${f_reset}"
git clone $cmd
echo "${T_GREEN}❯ ${T_YELLOW}Changing dir...${f_reset}"
cd $dir