#!/bin/bash

add_source() {
  if [ -f "$1" ]; then
    . "$1"
  fi
}

which_os() {
  case "$(uname -s)" in
    Darwin*)  echo "OSX" ;;
    Linux*)   echo "LINUX" ;;
    CYGWIN*)  echo "WINDOWS" ;;
    MINGW*)   echo "WINDOWS" ;;
    *)        echo "UNKNOWN" ;;
  esac
}
