#!/bin/bash

HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase # Erase duplicates in history

#zsh history configurations
setopt append_history # Immediately append to the history file, not just when a term is killed
setopt share_history # Share history between all sessions
setopt hist_ignore_space # Don't record an entry starting with a space
setopt hist_ignore_all_dups # Delete old recorded entry if new entry is a duplicate
setopt hist_save_no_dups # Don't write duplicate entries in the history file
setopt hist_ignore_dups # Delete old recorded entry if new entry is a duplicate
setopt hist_find_no_dups # Do not display a line previously found
setopt hist_reduce_blanks # Remove superfluous blanks from each command line being added to the history list
setopt hist_expire_dups_first # Delete duplicates first when HISTFILE size exceeds HISTSIZE
